### ISSUE TITLE
Update Style implementation in libs

### ISSUE THREAD

**Issue by ricardobrg** [tiki/style#21]
As a developer I need to use the tiki_style lib from pub for all libs.

Update the following libs with tiki_style from pub
~zendesk_flutter~
~upvoty~
~money~
~decision~
user_account
login 
~info_carousel~
spam_cards
~microsoft_provider~
~google_provider~

Acceptance criteria:
1 - New tag for each one of this libraries using tiki_style. 
2 - Reference the commit that merged the code into main in the comments.

**Comment by NickkTMD** [comment]
zendesk: https://github.com/tiki/zendesk_flutter/pull/28

**Comment by NickkTMD** [comment]
decision: https://github.com/tiki/decision/pull/34

**Comment by NickkTMD** [comment]
@ricardobrg

**Comment by NickkTMD** [comment]
**user_account**: https://github.com/tiki/user_account/pull/27
**upvoty**: https://github.com/tiki/upvoty/pull/22
@ricardobrg

**Comment by ricardobrg** [comment]
google_provider: https://github.com/tiki/google_provider/pull/57
microsoft_provider: https://github.com/tiki/microsoft_provider/pull/34
